language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.1.2
before_script:
  - dotnet restore
script:
  - dotnet build HoustonOnWire.sln -c Release

notifications:
  slack: grizli:bpa6vHF2LZbZnhqTt9OIT3Jg